services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: node:18.16-alpine
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
      - koala

