version: '3.8'

networks:
  koala: {}
services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=koala
      - POSTGRES_PASSWORD=koala
      - POSTGRES_DB=koala
    ports:
      - 5432:5432
    volumes:
      - ./infras/db/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - koala